### ISSUE TITLE
Can you give me access to this project?

### ISSUE THREAD

**Issue by Jibec** [YunoHost-Apps/kresus_ynh#14]
Hi, I would find it easier to have a "testing" branch here to work directly in this branch and asking review from @LowMem and @ZeHiro when making a pull request from testing to master.

would it be fine for your?

**Comment by LowMem** [comment]
Please note that there are also **tags** corresponding to each release. ;)

I have just added a new branch named ``testing``, copy of current ``master`` branch.

As far as I know, @Jibec, you already are part of Kresus team. But Kresus team here is not linked to kresus_ynh repository.
So that I have asked YunoHost-Apps team to link kresys_ynh repo to Kresus team. Wait and see ! ;)

**Comment by Jibec** [comment]
thank you @LowMem
