### ISSUE TITLE
Error upgrading to 0.18.1~ynh7 (in the Typescript compilation)

### ISSUE THREAD

**Issue by matthias4217** [YunoHost-Apps/kresus_ynh#140]
### Describe the bug

I've upgraded my Yunohost serer from 4.3 to 11 today (passing through 4.4). However, the Kresus upgrade (`0.18.1~ynh3` to `0.18.1~ynh7`) has failed. 
It seems that the error is related to `'getDefaultEnglishTranslator' is not exported by shared/helpers.ts, imported by client/helpers/index.ts`. App restoration seem to work fine.

### Context

- Hardware: VPS bought online
- YunoHost version: `11.0.9.15`
- I have access to my server: Through SSH and through the webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: No
- Using, or trying to install package version/branch: `0.18.1~ynh7`
- If upgrading, current package version: `0.18.1~ynh3`

### Steps to reproduce

```sh
sudo yunohost app upgrade kresus
```

### Logs

https://paste.yunohost.org/raw/useruxoyib

**Comment by nicofrand** [comment]
@yalh76 Hi! Can you explain why you added this: https://github.com/YunoHost-Apps/kresus_ynh/blob/bfca5e68f7160d94ed72252bc70654218ea97487/scripts/upgrade#L193 ?

This should not be needed, the package downloaded is already built…

**Comment by yalh76** [comment]
> @yalh76 Hi! Can you explain why you added this:
> 
> https://github.com/YunoHost-Apps/kresus_ynh/blob/bfca5e68f7160d94ed72252bc70654218ea97487/scripts/upgrade#L193
> ?

I though it was required because the package downloaded is from the source code, and I didn't though the .tar.bz2 provided could be already ...
![image](https://user-images.githubusercontent.com/30271971/195417420-a24781de-0812-4865-ac2a-3ad57e8fdbdc.png)

In addition, the command comes from: https://framagit.org/kresusapp/kresus/-/blob/0.18.1/support/docker/Dockerfile-nightly#L49

and [package check was OK](https://github.com/YunoHost-Apps/kresus_ynh/pull/139)


Reading the provided logs, I see weird stuff, 
It speaks of a `webpack.config.js` file but this file no more exists since Kresus 18.0
It complains not having:
- webpack
- copy-webpack-plugin
- mini-css-extract-plugin
- webpack-spritesmith

So I think the issuer is:
@matthias4217 installed a kresus version < 0.18
One day he upgraded to Kresus 0.18.1~ynh3, at that time sources weren't fully replaced, it just replaced new files keeping removed files from versions < 0.18, including the `webpack.config.js`, there wasn't `yarn build:prod` so no issue

https://github.com/YunoHost-Apps/kresus_ynh/blob/a4012aecf22d88fe84624a7feb03cf3e15e7bb4a/scripts/upgrade#L104-L115

In my [PR](https://github.com/YunoHost-Apps/kresus_ynh/pull/139), I fully [replace the sources](https://github.com/YunoHost-Apps/kresus_ynh/blob/6914c9f6e1fba0ca40e6cd558798f8453c4f18c3/scripts/upgrade#L105-L120) and later do `yarn build:prod`

The point is the fully replacement of the source is only made for version < 0.18.1 not for 0.18.1~ynh1, 0.18.1~ynh2, 0.18.1~ynh3, 0.18.1~ynh4, etc ....
