### ISSUE TITLE
Harden systemd unit ?

### ISSUE THREAD

**Issue by ZeHiro** [YunoHost-Apps/kresus_ynh#20]
Hello,

A contributor as packaged Kresus for Archlinux, and proposed this systemd unit. Maybe we could copy it:

https://git.archlinux.org/svntogit/community.git/tree/trunk/kresus.service?h=packages/kresus

**Comment by Jibec** [comment]
I'm unsure we should go in such a high level of integration with Systemd because I lack the knowledge on the potential side effects of such options.
I'll create a branch to test this, but to be honest, this sounds like too much protection for an application already protected by the YunoHost SSO (not exposed to the internet).

**Comment by Jibec** [comment]
Starting at page 34:
https://www.redhat.com/files/summit/session-assets/2017/S103870-Demystifying-systemd.pdf


NoNewPrivileges=true
> Ensure a process & children cannot elevate privileges

PrivateDevices=true
> If enabled, creates a private /dev namespace.
>> Includes pseudo devices like /dev/null, /dev/zero, etc
>> Disables CAP_MKNOD

PrivateTmp=true
> File system namespace with /tmp & /var/tmp (Files are under /tmp/systemd-private-*-[unit]-*/tmp)

ProtectHome=true
> If enabled, /home, /root, /run/user will appear empty
> Alternatively can set to “read-only”

ProtectSystem=strict
> If enabled, /usr & /boot directories are mounted read-only
> If “full”, /etc is also read-only

ProtectControlGroups=yes
> Takes a boolean argument. If true, the Linux Control Groups (cgroups(7)) hierarchies accessible through /sys/fs/cgroup will be made read-only to all processes of the unit. Except for container managers no services should require write access to the control groups hierarchies; it is hence recommended to turn this on for most services. For this setting the same restrictions regarding mount propagation and privileges apply as for ReadOnlyPaths= and related calls, see above. Defaults to off. If ProtectControlGroups= is set, MountAPIVFS=yes is implied.

ProtectKernelModules=yes
>     Takes a boolean argument. If true, explicit module loading will be denied. This allows module load and unload operations to be turned off on modular kernels. It is recommended to turn this on for most services that do not need special file systems or extra kernel modules to work. Defaults to off. Enabling this option removes CAP_SYS_MODULE from the capability bounding set for the unit, and installs a system call filter to block module system calls, also /usr/lib/modules is made inaccessible. For this setting the same restrictions regarding mount propagation and privileges apply as for ReadOnlyPaths= and related calls, see above. Note that limited automatic module loading due to user configuration or kernel mapping tables might still happen as side effect of requested user operations, both privileged and unprivileged. To disable module auto-load feature please see sysctl.d(5) kernel.modules_disabled mechanism and /proc/sys/kernel/modules_disabled documentation. If turned on and if running in user mode, or in system mode, but without the CAP_SYS_ADMIN capability (e.g. setting User=), NoNewPrivileges=yes is implied.

ReadWritePaths=/etc/webapps/kresus/config.ini /var/lib/kresus

Other subjects covered in in the PDF

- PrivateNetwork= Creates a network namespace with a single loopback device
- JoinsNamespaceOf= Enables multiple units to share PrivateTmp=  PrivateNetwork=
- SELinuxContext= Specify an SELinux security context for the process/service
- ReadWriteDirectories=, ReadOnlyDirectories=, InaccessibleDirectories= Configure file system namespaces
- CapabilityBoundingSet= CAP_SYS_ADMIN ~CAP_NET_ADMIN  (see man:capabilities(7) for details)


I'm unsure to understand why use ReadWriteDirectories or ReadWritePaths.

I'm unsure if Debian 9 has a "modular kernel" (see ProtectKernelModules)

My understanding is that it should be safe to use all of this with Kresus, but I think it's other application in the server that should be protected so they can't access to Kresus data.

**Comment by ArchangeGabriel** [comment]
I don’t think there is such a thing as “too much” protection, at least as long as said protections don’t have impact on usability or performances.

ReadWritePaths are used because we set ProtectSystem to `strict`, which effectively makes most of the system `ro`.

All linux distros have a modular kernel AFAIK, because linux is modular (you can see loaded modules at a given time by running `lsmod`).

Every application should be protected from each other if they don’t require to interact. You can protect Kresus by having its file owned by a dedicated user and with the right permissions (that’s partially what we do on ArchLinux, since I realized while writing this that we have 755 permissions on the home folder of kresus), but that won’t protect it from other processes gaining enough privileges to access Kresus data. So, a good system is one where every process is hardened as tightly as possible.

And you also don’t want Kresus to read data from other app of course.

**Comment by Jibec** [comment]
Thanks for your feekback @ArchangeGabriel 

It's in testing: https://github.com/YunoHost-Apps/kresus_ynh/commit/1f01df287a659e6a629fb90d94657a65eefd9aa8
Please test and confirm it works fine :)

**Comment by Jibec** [comment]
fixed by https://github.com/YunoHost-Apps/kresus_ynh/pull/21
